spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  client:
    #Eureka ????? ??? Eureka ??? ???? ??? ?????.
    #?? ??? ?????(??) ??? ??? ?, ??? ????? ??? Eureka ??? ???? ?? ???? ?? ?? ? ?? ?
    #false? ????, ? ?????? Eureka ??? ??? ??? ???? ????, ?? ???? ? ????? ?? ? ??
    register-with-eureka: false
    #Eureka ?????? Eureka ???? ????? ??? ???? ??? ??
    #Eureka ??? ??? ?????? ????, ?????? ?? ???? ??? ? ??? ? ? ??
    #false? ????, ? ?????? Eureka ???? ????? ??? ????? ????, ?? ???? ??? ? ? ??
    fetch-registry: false