spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        # git? ???? ? ?? file? ???? ??? ??? ?? ??
#        native:
#          search-locations: file://C:\Users\USER\MSA-STUDY-CONFIG
          #?? git? ???? ??



server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh