spring:
  application:
    name: spring-gateway-service
  cloud:
    gateway:
      routes:
        - id: first-service
        #  uri: http://localhost:8081
          uri: lb://MY-FIRST-SERVICE
          predicates:
            - Path=/first-service/**
          filters:
            - StripPrefix=1  # /first-service 라는 경로로 요청을 보내게 됨 즉 /first-service 경로를 제거함
            - name: CustomFilter
#            - AddRequestHeader=first-request, first-requests-header2
#            - AddResponseHeader=first-response, first-response-header2
        - id: second-service
         # uri: http://localhost:8082
          uri: lb://MY-SECOND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            - StripPrefix=1  # /second-service 라는 경로로 요청을 보내게 됨 즉 /second-service 경로를 제거함
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway LoggingFilter
                preLogger: true
                postLogger: true
#            - AddRequestHeader=second-request, second-requests-header2
#            - AddResponseHeader=second-response, second-response-header2
        - id: user-service
          uri: lb://USER-SERVICE # Eureka Server에 등록된 이름 즉 그 서비스의 spring.application.name 이다
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true



server:
  port: 8000


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #Eureka ??? URL? ?????. Eureka ?????? ? URL? ???? Eureka ??? ?????.
      defaultZone: http://localhost:8761/eureka