spring:
  application:
    name: order-service
  h2:
    console:
      enabled: true
      settings:
        #로컬 네트워크에서 다른 컴퓨터들이 H2 데이터베이스 콘솔에 접근할 수 있게 됩니다.
        web-allow-others: true
      path: /h2-console
  datasource:
    #    profileSQL=true: Driver 에서 전송하는 쿼리를 출력합니다.
    #    logger=Slf4JLogger: Driver 에서 쿼리 출력시 사용할 로거를 설정합니다.
    #    MySQL 드라이버: 기본값은 System.err 로 출력하도록 설정되어 있기 때문에 필수로 지정해 줘야 합니다.
    #    MariaDB 드라이버: Slf4j 를 이용하여 로그를 출력하기 때문에 설정할 필요가 없습니다.
    #    maxQuerySizeToLog=999999: 출력할 쿼리 길이
    url: jdbc:mysql://localhost:3306/MSA_MVC?profileSQL=true&logger=Slf4JLogger&useSSL=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&maxQuerySizeToLog=999999
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    hikari:
      connection-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        #Spring Boot가 애플리케이션 시작 시점에 데이터베이스 스키마를 자동으로 생성
    generate-ddl: true
    #설정을 사용하여 데이터베이스 초기화를 JPA가 스키마를 생성한 후에 실행하도록 할 수 있습니다.
    defer-datasource-initialization: true


server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
logging:
  level:
    sql: debug