spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      port: 9080
      settings:
        #로컬 네트워크에서 다른 컴퓨터들이 H2 데이터베이스 콘솔에 접근할 수 있게 됩니다.
        web-allow-others: true
      path: /h2-console
  r2dbc:
    url: r2dbc:mysql://localhost:3306/msa?useSSL=false&serverTimezone=UTC&profileSQL=true
    username: root
    password: 1234
    driver-class-name: io.r2dbc.mysql.MySqlConnectionFactoryProvider
  data:
    r2dbc:
      repositories:
        enabled: true


server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

greeting:
  message: Welcome to the Simple E-commerce.
token:
  expiration_time: 86400000
  secret: hisIsASecretKeyForJwtTokenAndItIsLongEnoughToMeetTheRequirementOfHS512AlgorithmHS512AlgorithmHS512Algorithm